config/routes.rb
Rails.application.routes.draw do
  get 'home/show'
  get '/search', to: "home#search"

  resources :students
  root 'home#show'
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end

  def search
    query = params[:query]
    @student = Student.find_by_email(query)

    if @student 
      flash[:notice] = "Student found"
    else
      flash[:alert] = "No Student found"
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find_by_id(params[:id])
  end

  def update
    student = Student.find_by_id(params[:id])

    if student.update_attributes(params[:student])
      # student was updated successfully
      flash[:notice] = "Student was update successfully!"
      redirect_to student_path(student)
    else
      # student was not updated show error message
    end
  end

  def create
    @student = Student.new(params[:student])

    if @student.save
      # student was saved successfully
      flash[:notice] = "Student was saved successfully!"
      redirect_to action: "index"
    else
      # student was not saved due to an error
    end
  end

  def show
    # Example request: /students/3
    # get the id from the params hash
    # and then use find_by_id to look for student with that id
    @student = Student.find_by_id(params[:id])
  end

  def destroy
    # find the id of student we want to delete
    @student = Student.find_by_id(params[:id])
    @student.destroy
    # display a flash message in index view
    flash[:notice] = "Student was destroyed"
    redirect_to students_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/search.html.erb
<% if @student %>
 <%= link_to @student.name, student_path(@student) %>
<% end %>

app/views/home/show.html.erb
<%= form_tag("/search", method: "get") do %>
  <%=label_tag(:query, "Search:") %>
  <%=text_field_tag(:query) %>
  <%=submit_tag("Submit") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NycdaCms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= flash[:notice] if flash[:notice] %>
  <%= flash[:alert] if flash[:alert] %>

  <%= yield %>

</body>
</html>

app/views/students/edit.html.erb
<h1>Edit student</h1>

<%= form_for @student, url: {action: "update"} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br/>

  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <br/>
  <%= f.submit "Update Student" %>
<% end %>

app/views/students/index.html.erb
<% @students.each do |student| %>
  <p><span><%= link_to student.email, student_path(student) %></span> <span><%= student.name %></span> <span><%= link_to "Delete Student", student_path(student), method: :delete, data: {confirm: "Are you sure you want to delete this student???"} %></span></p>
<% end %>

app/views/students/new.html.erb
<h1>Create a new student</h1>

<%= form_for @student, url: {action: "create"} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br/>

  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <br/>
  <%= f.submit "Add New Student" %>
<% end %>

app/views/students/show.html.erb
<p><span>Id: </span><%=@student.id %></p>
<p><span>Name: </span><%=@student.name %></p>
<p><span>Email: </span><%=@student.email %></p>
<p><span>Phone: </span><%=@student.phone %></p>
<p><span>Tuition Paid?: </span><%=@student.tuition_paid %></p>

<%= link_to "Edit Student", edit_student_path(@student) %>